spring:
  profiles:
    include: kafka
  kafka: 
    jaas:
      login-module:  "org.apache.kafka.common.security.plain.PlainLoginModule"
      enabled: true
    properties:
      security.protocol: "SASL_PLAINTEXT"
      ssl:
        protocol: "SASL_PLAINTEXT"
      sasl:
        mechanism: "PLAIN"
        jaas:
          config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${KAFKA_USERNAME}\" password=\"${KAFKA_PASSWORD}\";"


